### ISSUE TITLE
style NAV title so it matches tab colors

### ISSUE THREAD

**Issue by Antraeus** [Antraeus/project_knittable#98]
- About.html
  
  ```
  Tab color needs to be matching nav bar's PROJECT: Knittable
  ```
- Design.html
  
  ```
  Tab color needs to be matching nav bar's PROJECT: Knittable
  ```

![screen shot 2015-04-22 at 5 21 12 pm](https://cloud.githubusercontent.com/assets/6374437/7288287/18994c14-e914-11e4-8144-23969a064c7b.png)
![screen shot 2015-04-22 at 5 22 34 pm](https://cloud.githubusercontent.com/assets/6374437/7288292/2f5c6d14-e914-11e4-86c2-1f1d98a2bc0d.png)

**Comment by mollyfish** [comment]
Taken care of in issue 101
