### ISSUE TITLE
style thematically appropriate h1 boxes 

### ISSUE THREAD

**Issue by Antraeus** [Antraeus/project_knittable#99]
- Enlarge Design h1 or decrease the size of other page h1s
- Add a border that matches the corresponding .html's nav bar placard onto each h1 so that it matches design.html
- Needs more overall cohesion

---
## ![screen shot 2015-04-22 at 5 29 05 pm](https://cloud.githubusercontent.com/assets/6374437/7288378/922365c8-e915-11e4-8c9e-d96e23a7fea9.png)

![screen shot 2015-04-22 at 5 29 16 pm](https://cloud.githubusercontent.com/assets/6374437/7288379/974ce150-e915-11e4-93f3-3273bd932cf6.png)

**Comment by mollyfish** [comment]
Taken care of in issue 101
